{{- $env := .Values.env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: botpress-service-environment-configmap
  labels:
    {{- include "botpress-service-chart.labels" . | nindent 4 }}
data:
  environment_az: "Development"
  WEBSITE_TIME_ZONE: "America/Bogota"
  ASPNETCORE_ENVIRONMENT: "Development"
  BP_CONFIG_DATABASE_URL: {{.Values.environment.DATABASE_URL}}
  EXTERNAL_URL: 'https://{{.Values.host}}/botpress-service{{ if ne $env ""  }}-{{ $env }}{{ end }}' 
  BP_CONFIG_HTTPSERVER_EXTERNALURL: 'https://{{.Values.host}}/botpress-service{{ if ne $env ""  }}-{{ $env }}{{ end }}' 
  BP_PRODUCTION: '{{.Values.environment.BP_PRODUCTION}}'
  BPFS_STORAGE: {{.Values.environment.BPFS_STORAGE}}
  BP_REDIS_SCOPE: {{.Values.environment.BP_REDIS_SCOPE}}
  REDIS_URL: {{.Values.environment.REDIS_URL}}
  CLUSTER_ENABLED: '{{.Values.environment.CLUSTER_ENABLED}}'

