{{- $env := .Values.env -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "botpress-service-chart.serviceAccountName" . }}-sa{{ if ne $env ""  }}-{{ $env }}{{ end }}
  labels:
    {{- include "botpress-service-chart.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId }}
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}   
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
